#!groovy

/*
  Script pipeline para construção do ambiente Citsmart

  Autor: Ivan Santos (contato@ivan.consulting)
  Autor: Otávio Lemos (otavio.lemos@citsmart.com)

  Rancher Keys:
  Environment: <NOME DO ENVIRONMENT>
  Access Key: A548DA390D2002F8B5AD
  Secret Key: HjuzzUvpEzqWqJMK44RQn1AvCfuJ1pCB6sePKqhW
  
  TODO: 

*/

def ambiente
def localizacao

node {
  //rocketChat("DevOps: Pipeline: Iniciando Build")    

  stage ('Preparação do ambiente') {

    rocketChat("Preparando o ambiente > Nome")
    
    def envName = input(
      id: 'nomeAmbiente', message: 'Nome do ambiente',
      ok: 'Criar!',
      parameters: [
      [$class: 'TextParameterDefinition', defaultValue: 'citsmart', description: 'Entre com o nome do ambiente', name: 'nome']
    ])

    echo ("Ambiente a ser criado: "+ envName['nome'])
    //ambiente = envName['nome']
 }

 stage('Criando Infraestrutura'){
    rocketChat("Stage [Criando Infraestrutura]:Executando Route53")    

    rocketChat("Stage [Criando Infraestrutura]:Executando criação de instancias")

    rocketChat("Stage [Criando Infraestrutura]:Executando criação de volumes NFS")

 }


 stage ("Adicionando Host Rancher Server") {
    rocketChat("Adicionando instancia ao Environment" + ambiente['nome'] )    
    
    // Executar comando SSH dentro da instancia e iniciar rancher-agent
    echo "Executar comando SSH dentro da instancia e iniciar rancher-agent"

    
    docker.withServer('tcp://192.168.0.17:2375') {
      sh 'docker run '
    }

 }

  stage ("Executar STACK") {
    rocketChat("Criando STACK")    
    docker.withServer('tcp://192.168.0.17:2375') {
       rancher('up stack') 
    }

 }


 stage ('Verificação Stacks'){
        vrfRancherStack("citsmart")
 }

deleteDir()
}


def rocketChat(msg) {
    rocketSend channel: 'citsmart-env-create', message: "Build: ${env.BUILD_NUMBER}: ${msg}", rawMessage: true
}

def rancherCli(cmd) {
    sh "docker run --rm -i -e CATTLE_URL='http://http://192.168.0.17:8080' -e CATTLE_ACCESS_KEY='CBB404EDF2389806B2C3' -e CATTLE_SECRET_KEY='cff6Xkb1nGt1pLt4aRPKZKRbGNHC6YK4epqhY6hN' hub.docker.planejamento.gov.br/rancher-cli ${cmd}"
}

def rancher(cmd){
    sh "docker run --rm -i -e RANCHER_URL='http://http://192.168.0.17:8080' -e RANCHER_SERVER_URL='http://192.168.0.17:8080' -e RANCHER_ACCESS_KEY=CBB404EDF2389806B2C3 -e RANCHER_SECRET_KEY=cff6Xkb1nGt1pLt4aRPKZKRbGNHC6YK4epqhY6hN rancher/cli ${cmd}"
}


def vrfRancherStack(stack){
    rocketChat("Validando Stack no Rancher DTH:\n" + stack)   
    echo("Verificando STACK: "+ stack )
    
    docker.withServer('tcp://192.168.0.17:2375'){
        def stackHomStatus = sh(returnStdout: true, script: "docker run --rm -i -e RANCHER_URL='http://http://192.168.0.17:8080' -e RANCHER_SERVER_URL='http://192.168.0.17:8080' -e RANCHER_ACCESS_KEY=CBB404EDF2389806B2C3 -e RANCHER_SECRET_KEY=cff6Xkb1nGt1pLt4aRPKZKRbGNHC6YK4epqhY6hN rancher/cli stack ls | grep ${stack} | awk '{print \$3}'").trim()
        echo ('STATUS STACK: ' + stack +': ' + stackHomStatus)
        if (stackHomStatus != 'healthy' ) {
            echo "Inicializando container"
            rocketChat("STACK: "+ stack+ ":DOWN -- INICIANDO ...")
            // Problemas ao executar o UP
            //rancher("up --stack "+${stack})
            rancher("start "+${stack})
        } else {
            echo "STACK Funcional"    
            rocketChat("Stack " + stack + " (Rancher DTH) = OK ")   
        }
    }
}